version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: userManagement
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Sa1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql